//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrangSuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangChiTiet
    {
        public int ID { get; set; }
        public Nullable<int> IDDonHang { get; set; }
        public Nullable<int> IDSanPham { get; set; }
        public Nullable<int> SoLuongSanPham { get; set; }
        public Nullable<int> GiaSanPham { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
