//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrangSuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.DonHangChiTiets = new HashSet<DonHangChiTiet>();
            this.HinhSanPhams = new HashSet<HinhSanPham>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public string HinhSanPham { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> IDLoaiSanPham { get; set; }
        public string MoTaSanPham { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
        public Nullable<bool> TrangThaiSanPham { get; set; }
        public Nullable<System.DateTime> NgayTaoSanPham { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangChiTiet> DonHangChiTiets { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhSanPham> HinhSanPhams { get; set; }
    }
}
